In [2]:
import numpy as np 

In [5]:
data1 = [6, 7.5, 8, 0, 1]
array1 = np.array(data1)
array1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [17]:
print(np.ndim(array1))
print(np.shape(array1))
print(np.size(array1))
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 2)))


1
(5,)
5
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[  6.90960092e-310   1.01638315e-316]
  [  5.07688647e+231   5.28599403e-085]
  [  2.00294893e-313   5.07688647e+231]]

 [[  5.28599403e-085   3.26710941e-313]
  [  1.71124621e+243   4.03179200e-313]
  [  2.69316350e-110   1.08694442e-322]]]


In [34]:
 #acts like python range function
np.arange(15)
arr1 =  np.array(3,dtype=np.int32)
print(arr1)
print(arr1.dtype)


3
int32


In [38]:
float_arr = arr1.astype(np.float64)
print(float_arr.dtype)

float64


In [43]:
##Array vectorization Group of operations
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr*arr


array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [48]:
##scalars
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
1/arr
arr*5



array([[  5.,  10.,  15.],
       [ 20.,  25.,  30.]])

In [63]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr[0]=43
arr[1:6]



array([[ 4.,  5.,  6.]])

In [71]:
from sklearn.datasets import load_iris
##iris_dataset prints dictionary values
iris_dataset = load_iris()
##keys of iris_dataset
iris_dataset.keys()
##feature_names(column_names) ['sepal length (cm)','sepal width (cm)','petal length (cm)', 'petal width (cm)']
iris_dataset['feature_names']




['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [79]:
##shape is number of samples(rows) multiplied by number of features(columns)
iris_dataset['data'].shape


(150, 4)

In [82]:
##Target  0 means setosa, 1 means versicolor, 2 means virginica
iris_dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [1]:
from sklearn.model_selection import train_test_split